### ISSUE TITLE
Works well with API level below 16

### ISSUE THREAD

**Issue by embydextrous** [DavidPacioianu/InkPageIndicator#13]
Not exactly an issue.

But most of the new apps in India are targeting API 15 or above.

And this can be made compatible with API 14 and above by replacing:

`postInvalidateOnAnimation()` with

'ViewCompat.postInvalidateOnAnimation(InkPageIndicator.this)'

**Comment by DavidPacioianu** [comment]
Thank you! I have just added it in the last version.
