### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by adi1133** [DavidPacioianu/InkPageIndicator#15]
Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@label value=(Kapt Issue) from AndroidManifest.xml:6:9-35
>     is also present at [com.pacioianu.david:ink-page-indicator:1.2.0] AndroidManifest.xml:12:9-41 value=(@string/app_name).
>     Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:4:5-14:19 to override.

**Comment by kiezkicker** [comment]
In what version can I find the fix for the manifest merge issue? Version 1.2.0 is not working for me.

**Comment by adi1133** [comment]
In the pull request from above.
