### ISSUE TITLE
Add tags to custom library view attributes

### ISSUE THREAD

**Issue by dniHze** [DavidPacioianu/InkPageIndicator#17]
In some cases, names of own attributes or attributes in other libraries can be equal with your library attributes. That's why resource merger could exit with an error while building. Like this: 

> Attribute "animationDuration" has already been defined

I propose you to add tags like `pi_animationDuration` to your attributes. That's might be helpful.

**Comment by DavidPacioianu** [comment]
@dniHze Thank you for pointing this out. I have just updated the library with a new naming for the attributes. I added the "**ipi**_" tag to all the previous attributes.
