### ISSUE TITLE
Dot disappears when you begin to scroll to left but stop

### ISSUE THREAD

**Issue by guiwro** [DavidPacioianu/InkPageIndicator#5]
Step to reproduce:

Create a ViewPager with 3 pages.
Go to the second page.
Begin to scroll to the first page, but stop the movement so that you actually stay on the second.
The first dot disappears.

The bug doesn't show when you slide to right.

**Comment by DavidPacioianu** [comment]
I can't reproduce it on my phone. On what version of android are you testing it? Have you found anything that can help us solving this bug?

**Comment by guiwro** [comment]
You're right, it was a problem with my code.
